name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Download References
        uses: Axwabo/scpsl-references-downloader@v1
        with:
          branch: ${{ vars.BRANCH }}
      - name: Build LabAPI
        run: dotnet build -c Release -o Output
      - name: Build EXILED
        run: dotnet build -c "Exiled Release" -o Output
      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            "Output/MeowDebugger.dll"
            "Output/MeowDebugger-Exiled.dll"
