name: Release DLL and Nuget Package
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build-and-release:
    runs-on: windows-2022
    environment: publish

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: actions/checkout@v4
      - name: Restore Packages
        run: nuget restore MeowDebugger.slnx

      - name: Download References
        run: Invoke-WebRequest -Uri "https://exmod-team.github.io/SL-References/Dev.zip"
          -OutFile "References.zip"

      - name: Extract Refs
        run: |
          mkdir MeowDebugger\lib
          tar -xf References.zip -C MeowDebugger/lib

      - name: Build EXILED
        run: msbuild MeowDebugger.slnx /p:Configuration="Exiled Release" /p:Platform=x64 /m

      - name: Build LabAPI
        run: msbuild MeowDebugger.slnx /p:Configuration=Release /p:Platform=x64 /m

      - name: Create Release with Dlls
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          generate_release_notes: false
          files: |
            MeowDebugger/bin/x64/Exiled Release/net48/MeowDebugger-Exiled.dll
            MeowDebugger/bin/x64/Release/net48/MeowDebugger.dll
